### ISSUE TITLE
Re-downloads files in root directory

### ISSUE THREAD

**Issue by ProbieK** [cwh1te/AutoTraverse#1]
Files in the root download directory get re-downloaded every time the script runs.
I don't believe that the files in the root directory are getting written to the .manifest file.

**Comment by cwh1te** [comment]
Finally got around to rewriting this - if you still use it, let me know how this new version treats you.

**Comment by cwh1te** [comment]
Just made another big update cd9a9772b294a54b947fb0772709e324149f6414, but this one breaks compatibility with the old way of tracking files and introduces a JSON-based manifest.
Since at this point basically all of the code relevant to this issue has been replaced, I'm going to go ahead and close it.
